// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://alovdlgbyhvdjavdtwfm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFsb3ZkbGdieWh2ZGphdmR0d2ZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzI4MDY4MjksImV4cCI6MjA0ODM4MjgyOX0.qE70pI7VV2hufVCwSbBBeGmKyfu-5zp5wYXogkhDq5g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);